### ISSUE TITLE
Issue with pyhpecw7

### ISSUE THREAD

**Issue by yoanndu67** [HPENetworking/pyhpecw7#14]
Hello guy,

I'm currently trying to implement the pyhpecw7 library.
But i've got an issue while doing device.open()
Maybe it's juste because the device is not supported but I'd prefer asking.

I've got an HP5940 on Version 7.1.070, Release 2510P01
netconf is enabled, and I can reach my device on port 830  (by netconf over ssh directly from CLI)

The issue :
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyhpecw7-0.0.9-py2.7.egg/pyhpecw7/comware.py", line 117, in open
    raise ConnectionError(self, msg='There was an unknown error while trying to connect.')
pyhpecw7.errors.ConnectionError: ConnectionError: host: hrx5940, port: 830 msg: There was an unknown error while trying to connect.

Thanks in advance,

Yoann

**Comment by casevh** [comment]
I also encountered this error and identified the cause of the error. The default value for the `ssh_config` parameter that is passed to ncclient.manager.connect is set to False by HPCOM7. But the default value should be `None`. The workaround is to add `ssh_config=None` to the arguments for `HPCOM7()`.

I'll try to work on a PR to fix the underlying cause.

casevh

**Comment by yoanndu67** [comment]
Casevh, thanks for your reply and indeed, it was the "trick".
When passed ssh_config=None to my HPCOM7, I could reach my 5940 device with pyhpecw7.
So I decided to add it globally ( because I'd like working on some ansible playbook which are using pyhpecw7)

Edit comware.py on your pyhpecw7 directory

NEW :
def __init__(self, **kvargs):
        self.host = kvargs.get('host')
        self.username = kvargs.get('username')
        self.password = kvargs.get('password')
        self.port = kvargs.get('port') or 830
        self.timeout = kvargs.get('timeout') or 30
        self.ssh_config = kvargs.get('ssh_config', **None**)     <=={instead of ('ssh_config', False)}
        self.staged = []
        self._locked = False

After that, all of my playbook are working !
You made my day, thanks

Yoann

**Comment by eddy-obs** [comment]
Casevh,

Thank you for your answer, I'll test this weekend on the HPE 5130 comware 7.
Perfect for my ansible playbook using pyhpecw7.

I'm waiting for this good news !

Regards.

2018-04-13 8:53 GMT+02:00 yoanndu67 <notifications@github.com>:
