### ISSUE TITLE
pip3 install fails 

### ISSUE THREAD

**Issue by dlenwell** [HPENetworking/pyhpecw7#17]
NameError: name 'textfsm' is not defined is the error thrown by pip when trying to install gtextfsm 

this works fine in python 2.. 

`
✗ pip3 install git+git://github.com/HPENetworking/pyhpecw7.git
Collecting git+git://github.com/HPENetworking/pyhpecw7.git
  Cloning git://github.com/HPENetworking/pyhpecw7.git to /private/var/folders/wl/c0wr2fld75vf8k_wc3fy4blm0000gn/T/pip-req-build-78_8zm4x
Collecting gtextfsm==0.2.1 (from pyhpecw7==0.0.11)
  Using cached https://files.pythonhosted.org/packages/98/12/edfdccf3d968ffbb94ac8e48b3172395b6902eb4265bded0b0d07a1652f3/gtextfsm-0.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/wl/c0wr2fld75vf8k_wc3fy4blm0000gn/T/pip-install-9mwz34hk/gtextfsm/setup.py", line 19, in <module>
        import textfsm
      File "/private/var/folders/wl/c0wr2fld75vf8k_wc3fy4blm0000gn/T/pip-install-9mwz34hk/gtextfsm/textfsm/__init__.py", line 2, in <module>
        __version__ = textfsm.__version__
    NameError: name 'textfsm' is not defined
`

**Comment by adampav** [comment]
Hi. is there any new info about this? I want to use the library in python3 aswell.

**Comment by cshultz** [comment]
I am also running into this issue and would like to run this module under python3. Any update here?

**Comment by romchi** [comment]
Hi, this project will be migrated to python 3?

**Comment by johanreinalda** [comment]
To fix this:
git clone
modify setup.py, and remove the "gtextfsm" line from the install_require section after line 33
next run "python3 setup.py install"

**Comment by itrider-gh** [comment]
> To fix this:
> git clone
> modify setup.py, and remove the "gtextfsm" line from the install_require section after line 33
> next run "python3 setup.py install"

it's working thank you
